sap.ui.define([
    "./BaseController",
    "./Page.controller",
    "./AssignmentDataManager",
    "./DataTransformer",
    "./DateUtility",
    "./WeekCalendarModel",
    "./WeekCalendarDateHelper",
    "./WeekCalendarUtility"
]);
