export enum UserType {
    CONSULTANT = 'CONSULTANT3',
    CONFIGURATIONEXPERT = 'CONFIGURATIONEXPERT',
    RESOURCEMANAGER_VALIANT = 'RESOURCEMANAGER_VALIANT',
    NOT_IN_DB = 'NOT_IN_DB',
    HEALTH_CHECK = 'HEALTHCHECK',
    CF_SERVICE = 'CFSERVICE',
    NONE = 'NONE',
}
