import { demoDataSetupEnv } from './demoDataSetupEnv';

export const testEnvironment = new demoDataSetupEnv();
export const TEST_TIMEOUT = 1 * 120 * 1000;
export const EntityRepositoryGetterMap: Record<string, string> = {
    // skills
    COM_SAP_RESOURCEMANAGEMENT_SKILL_SKILLS: 'getSkillRepository',
    COM_SAP_RESOURCEMANAGEMENT_SKILL_SKILLS_TEXTS: 'getSkillTextRepository',
    COM_SAP_RESOURCEMANAGEMENT_SKILL_ALTERNATIVELABELS: 'getAlternativeLabelRepository',
    COM_SAP_RESOURCEMANAGEMENT_SKILL_CATALOGS: 'getCatalogRepository',
    COM_SAP_RESOURCEMANAGEMENT_SKILL_CATALOGS2SKILLS: 'getCatalogs2SkillsRepository',
    //Consultant Profle
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_HEADERS: 'getEmployeeHeaderRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKFORCEPERSON_WORKFORCEPERSONS: 'getWorkforcePersonRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKFORCEPERSON_EMAILS: 'getEmailRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKFORCEPERSON_PHONES: 'getPhoneRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKFORCEPERSON_PROFILEDETAILS: 'getProfileDetailRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKASSIGNMENT_WORKASSIGNMENTS: 'getWorkAssignmentRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKASSIGNMENT_WORKASSIGNMENTDETAILS: 'getWorkAssignmentDetailRepository',
    COM_SAP_RESOURCEMANAGEMENT_WORKFORCE_WORKASSIGNMENT_JOBDETAILS: 'getJobDetailRepository',
    COM_SAP_RESOURCEMANAGEMENT_RESOURCE_HEADERS: 'getResourceHeaderRepository',
    COM_SAP_RESOURCEMANAGEMENT_RESOURCE_CAPACITY: 'getResourceCapacityRepository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_PRIOREXPERIENCE_INTERNALWORKEXPERIENCE: 'getInternalWorkExperienceRespository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_PRIOREXPERIENCE_INTERNALWORKEXPERIENCESKILLS: 'getInternalWorkExperienceSkillRepository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_PRIOREXPERIENCE_EXTERNALWORKEXPERIENCE: 'getExternalWorkExperienceRespository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_PRIOREXPERIENCE_EXTERNALWORKEXPERIENCESKILLS: 'getExternalWorkExperienceSkillRepository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_PRIOREXPERIENCE_ROLEASSIGNMENTS: 'getRoleAssignmentRepository',
    COM_SAP_RESOURCEMANAGEMENT_EMPLOYEE_QUALIFICATIONS_SKILLASSIGNMENTS: 'getSkillAssignmentRepository',
    COM_SAP_RESOURCEMANAGEMENT_ORGANIZATION_DETAILS: 'getOrganizationDetailRepository',
    COM_SAP_RESOURCEMANAGEMENT_ORGANIZATION_HEADERS: 'getOrganizationHeaderRepository',
    COM_SAP_RESOURCEMANAGEMENT_ORGANIZATION_COSTCENTERS: 'getCostCenterRepository',
    COM_SAP_RESOURCEMANAGEMENT_CONFIG_PROJECTROLES: 'getProjectRoleRepository',
    COM_SAP_RESOURCEMANAGEMENT_CONFIG_PROJECTROLES_TEXTS: 'getProjectRoleTextRepository',
    COM_SAP_RESOURCEMANAGEMENT_SYSTEM_DATA_TIMEDIMENSION_DATA: 'getTimeDimensionsRepository',
    COM_SAP_RESOURCEMANAGEMENT_CONSULTANTPROFILE_INTEGRATION_AVAILABILITYREPLICATIONSUMMARY: 'getAvailabilityReplicationSummaryRepository',
    //Resource Request
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_BILLINGROLES: 'getBillingRoleRepository',
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_CUSTOMERS: 'getCustomerRepository',
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_DEMANDS: 'getDemandRepository',
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_PROJECTS: 'getProjectRepository',
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_WORKPACKAGES: 'getWorkPackageRepository',
    COM_SAP_RESOURCEMANAGEMENT_RESOURCEREQUEST_RESOURCEREQUESTS: 'getResourceRequestRepository',
    COM_SAP_RESOURCEMANAGEMENT_RESOURCEREQUEST_CAPACITYREQUIREMENTS: 'getCapacityRequirementRepository',    
    COM_SAP_RESOURCEMANAGEMENT_PROJECT_DEMANDCAPACITYREQUIREMENTS: 'getDemandCapacityRequirementRepository',
    //Assignment
    COM_SAP_RESOURCEMANAGEMENT_ASSIGNMENT_ASSIGNMENTBUCKETS: 'getAssignmentBucketRepository',
    COM_SAP_RESOURCEMANAGEMENT_ASSIGNMENT_ASSIGNMENTS: 'getAssignmentsRepository'
}
