package com.sap.c4p.rm.projectintegrationadapter.config;

import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

public enum LoggingMarker {

  REPLICATION_AUDIT_LOG_MARKER,
  SUPPLY_REPLICATION_MARKER,
  REPLICATION_CREATE_ASSIGNMENT_MARKER,
  REPLICATION_CHANGE_ASSIGNMENT_MARKER,
  REPLICATION_DELETE_ASSIGNMENT_MARKER,
  REPLICATION_CREATE_DEMAND_MARKER,
  REPLICATION_CHANGE_DEMAND_MARKER,
  REPLICATION_FETCH_DEMAND_MARKER,
  REPLICATION_DELETE_DEMAND_MARKER,
  REPLICATION_CREATE_PROJECT_MARKER,
  REPLICATION_CHANGE_PROJECT_MARKER,
  REPLICATION_FETCH_PROJECT_MARKER,
  REPLICATION_DELETE_PROJECT_MARKER,
  REPLICATION_CREATE_WORKPACKAGE_MARKER,
  REPLICATION_CHANGE_WORKPACKAGE_MARKER,
  REPLICATION_FETCH_WORKPACKAGE_MARKER,
  REPLICATION_DELETE_WORKPACKAGE_MARKER,
  REPLICATION_CREATE_RESOURCEREQUEST_MARKER,
  REPLICATION_CHANGE_RESOURCEREQUEST_MARKER,
  REPLICATION_FETCH_RESOURCEREQUEST_MARKER,
  REPLICATION_DELETE_RESOURCEREQUEST_MARKER,
  REPLICATION_CREATE_PROJECTREPLICATION_MARKER,
  REPLICATION_CHANGE_PROJECTREPLICATION_MARKER,
  REPLICATION_FETCH_PROJECTREPLICATION_MARKER,
  REPLICATION_DELETE_PROJECTREPLICATION_MARKER,
  REPLICATION_PROJECT_MANAGEMENT_S4_CLIENT_MARKER,
  REPLICATION_DESTINATION_ACCESS_MARKER,
  REPLICATION_SUBSCRIPTION_HANDLER_MARKER,
  REPLICATION_JOB_SCHEDULER_MARKER,
  REPLICATION_XSUAA_SERVICE_MARKER,
  REPLICATION_CF_UTIL_MARKER,
  LOGGING,
  REPLICATION_MASTER_DATA_REPLICATION_MARKER;

  public Marker getMarker() {
    return MarkerFactory.getMarker(this.toString());
  }
}
