general:
  buildTool: 'mta'
  productiveBranch: 'master'
  repository: 'Resource-Management'
  owner: 'Cloud4RM'
  vaultBasePath: 'piper/PIPELINE-GROUP-184'
  vaultPipelineName: 'PIPELINE-11117'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
  vaultTestCredentialEnvPrefix: ENV_
  vaultTestCredentialPath: secrets
  vaultTestCredentialKeys: [
                            # Azure token
                            'AZURE_PIPELINE_TOKEN',
                            # Artifactory credentials
                            'ARTIFACTORY_AUTH_TOKEN', 'ARTIFACTORY_PASSWORD', 'ARTIFACTORY_USERNAME',
                            # Github Token
                            'GITHUB_TOKEN',
                            # Hash Values for Service Broker
                            'CANARY_SERVICE_BROKER_HASH1', 'CANARY_SERVICE_BROKER_HASH2',
                            'EU10PREPROD_SERVICE_BROKER_HASH1', 'EU10PREPROD_SERVICE_BROKER_HASH2',
                            'EU11PREPROD_SERVICE_BROKER_HASH1', 'EU11PREPROD_SERVICE_BROKER_HASH2',
                            'EU10PROD_SERVICE_BROKER_HASH1', 'EU10PROD_SERVICE_BROKER_HASH2',
                            'US10PREPROD_SERVICE_BROKER_HASH1', 'US10PREPROD_SERVICE_BROKER_HASH2',
                            # Cloud Logging
                            'EU10PROD_CLOUD_LOGGING_EXCHANGE_KEY',
                            # ANS slack
                            'INTPROD_ANS_SLACK_WEBHOOK',
                            'EU10PROD_ANS_SLACK_WEBHOOK',
                            # Metering
                            'INTPROD_METERING_PROVIDER_TOKEN',
                            'EU10PROD_METERING_PROVIDER_TOKEN',
                            # Application Users
                            'CF_USER', 'CF_PASSWORD',
                            'CF_USER_DEV', 'CF_PASSWORD_DEV',
                            'CF_USER_EU10_PROD', 'CF_PASSWORD_EU10_PROD',
                            'USER_AUTHATTRTESTUSER01', 'PASSWORD_AUTHATTRTESTUSER01',
                            'USER_AUTHATTRTESTUSER02', 'PASSWORD_AUTHATTRTESTUSER02',
                            'USER_CONFIGURATIONEXPERT', 'PASSWORD_CONFIGURATIONEXPERT',
                            'USER_CONSULTANT','PASSWORD_CONSULTANT',
                            'USER_CONSULTANT3','PASSWORD_CONSULTANT3',
                            'USER_PROJECTMANAGER','PASSWORD_PROJECTMANAGER',
                            'USER_PROJECTMANAGER_AUTHORIZED','PASSWORD_PROJECTMANAGER_AUTHORIZED',
                            'USER_RESOURCEMANAGEMENTOPERATOR','PASSWORD_RESOURCEMANAGEMENTOPERATOR',
                            'USER_RESOURCEMANAGER','PASSWORD_RESOURCEMANAGER',
                            'USER_RESOURCEMANAGEMENTADMINISTRATOR','PASSWORD_RESOURCEMANAGEMENTADMINISTRATOR',
                            'USER_RESOURCEMANAGER_AUTHORIZED', 'PASSWORD_RESOURCEMANAGER_AUTHORIZED',
                            'USER_RESOURCEMANAGER_VALIANT', 'PASSWORD_RESOURCEMANAGER_VALIANT',
                            'USER_NOT_IN_DB', 'PASSWORD_NOT_IN_DB',
                            'USER_RESOURCEMANAGERUI', 'PASSWORD_RESOURCEMANAGERUI', 'CANARY_CONSUMER_CLIENT_ID','CANARY_CONSUMER_CLIENT_SECRET','EU10_PREPROD_SAAS_CLIENT_ID',
                            'EU10_PREPROD_SAAS_CLIENT_SECRET','EU11_PREPROD_SAAS_CLIENT_ID','EU11_PREPROD_SAAS_CLIENT_SECRET','US10_PREPROD_SAAS_CLIENT_ID','US10_PREPROD_SAAS_CLIENT_SECRET'
                            ]

stages:
  Build:
    karmaExecuteTests: false
    sonarExecuteScan: false
    kanikoExecute: false
    mtaBuild: true
  Integration:
    apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
    space: 'test-e2e'
    org: 'c4p-rm'
    dockerImage: 'ppiper/cf-cli:v10'
    mtaDeployParameters: '-f --strategy blue-green'
    mtaExtensionDescriptor: 'mta_extensions/mta-aws_canaray_e2e.mtaext'
  Acceptance:
    sapDownloadArtifact: true
    cloudFoundryDeploy: true
    apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
    space: 'test-uat'
    org: 'c4p-rm'
    dockerImage: 'ppiper/cf-cli:v10'
    mtaDeployParameters: '--skip-testing-phase -f --strategy blue-green'
    mtaExtensionDescriptor: 'mta_extensions/mta-aws_canaray_uat.mtaext'
  PreProductionCD:
    apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
    space: 'eu10-preprod-cd'
    org: 'c4p-rm-eu10-preprod'
    dockerImage: 'ppiper/cf-cli:v10'
    mtaDeployParameters: '-f --strategy blue-green'
    mtaExtensionDescriptor: 'mta_extensions/mta-aws-eu10-preprodcd.mtaext'
  PreProductionEU11CD:
    apiEndpoint: 'https://api.cf.eu11.hana.ondemand.com'
    space: 'eu11-preprod-cd'
    org: 'c4p-rm-eu11-preprod'
    dockerImage: 'ppiper/cf-cli:v10'
    mtaDeployParameters: '-f --strategy blue-green'
    mtaExtensionDescriptor: 'mta_extensions/mta-aws-eu11-preprodcd.mtaext'
  PreProductionUS10CD:
    apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
    space: 'us10-preprod-cd'
    org: 'c4p-rm-us10-preprod'
    dockerImage: 'ppiper/cf-cli:v10'
    mtaDeployParameters: '-f --strategy blue-green'
    mtaExtensionDescriptor: 'mta_extensions/mta-aws-us10-preprodcd.mtaext'
  Security:
    checkmarxExecuteScan: true
    fortifyExecuteScan: true
    detectExecuteScan: true
  IPScan and PPMS:    
    detectExecuteScan: false
    sapCheckPPMSCompliance: true
    sapCheckECCNCompliance: true
    
steps:
  artifactPrepareVersion:
    gitHttpsCredentialVaultSecretName: 'github'
  mtaBuild:
    mtaBuildTool: 'cloudMbt'
    mtarGroup: 'com.sap.c4p.rm'
    dockerImage: 'devxci/mbtci-java17-node18'
    projectSettingsFile: settings.xml
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-184-default'
  sapCumulusUpload:
    pipelineId: '1009f23d-57ea-41a9-a558-e15bf61f55c1'
  karmaExecuteTests:
    modules: ['./Assignment']
  fortifyExecuteScan:
    buildTool: 'maven'
    dockerImage: 'piper.int.repositories.cloud.sap/piper/fortify:jdk8'
    serverUrl: 'https://fortify.tools.sap/ssc'
    projectName: 'C4P-RM'
    version: 'Master'
    autoCreate: true
    buildDescriptorFile: ./pom.xml
    projectSettingsFile: settings.xml
    globalSettingsFile: '' # Workaround, setting globalSettings to empty for now
    exclude: ['**/tests/**/*', '**/approuter/**/*', '**/db/**/*', '**/flp-content/**/*', '**/ui-content/**/*', '**/Skill/tests/**/*', '**/Skill/app/**/*', '**/Skill/appouter/**/*', '**/Skill/db/**/*', '**/Skill/flp-content/**/*', '**/Skill/utils/**/*', '**/Skill/ui-content/**/*', '**/Skill/srv/src/test/**/*', '**/Assignment/tests/**/*', '**/Assignment/app/**/*', '**/Assignment/appouter/**/*', '**/Assignment/db/**/*', '**/Assignment/flp-content/**/*', '**/Assignment/utils/**/*', '**/Assignment/ui-content/**/*', '**/Assignment/srv/src/test/**/*', '**/Central-Services/tests/**/*', '**/Central-Services/app/**/*', '**/Central-Services/appouter/**/*', '**/Central-Services/db/**/*', '**/Central-Services/flp-content/**/*', '**/Central-Services/utils/**/*', '**/Central-Services/ui-content/**/*', '**/Central-Services/srv/src/test/**/*', '**/Central-Services/service-broker/**/*', '**/Central-Services/api-gateway/src/test/**/*', '**/Consultant-Profile/tests/**/*', '**/Consultant-Profile/app/**/*', '**/Consultant-Profile/appouter/**/*', '**/Consultant-Profile/db/**/*', '**/Consultant-Profile/flp-content/**/*', '**/Consultant-Profile/utils/**/*', '**/Consultant-Profile/ui-content/**/*', '**/Consultant-Profile/srv/src/test/**/*', '**/Consultant-Profile/integration-srv/src/test/**/*', '**/Resource-Request/tests/**/*', '**/Resource-Request/app/**/*', '**/Resource-Request/appouter/**/*', '**/Resource-Request/db/**/*', '**/Resource-Request/flp-content/**/*', '**/Resource-Request/utils/**/*', '**/Resource-Request/ui-content/**/*', '**/Resource-Request/srv/src/test/**/*', '**/Resource-Request/project-integration-adapter/src/test/**/*']
  detectExecuteScan:
    dockerImage: 'maven:3.6-jdk-8'
    projectName: 'SHC - RESOURCE MGT OD 1.0'
    customScanVersion: 'C4P-RM-Master'
    token: 'token'
    scanProperties: ['--detect.project.version.distribution=SaaS', '--detect.timeout=60000' , '--detect.detector.search.depth=0']
    customEnvironmentVariables: ['DETECT_LATEST_RELEASE_VERSION=7.14.0']
    minScanInterval: 1
    projectSettingsFile: 'settings.xml'
    scanPaths: ['db', 'approuter', 'Skill/srv', 'Resource-Request/srv', 'Assignment/srv', 'Central-Services/srv', 'Consultant-Profile/srv', 'Resource-Request/project-integration-adapter', 'Central-Services/api-gateway', 'Consultant-Profile/integration-srv', 'Central-Services/app/resourceOrganization', 'Central-Services/approuter', 'Assignment/flp-content', 'Assignment/app/capacityGridUi', 'Assignment/approuter', 'Assignment/ui-content']
  sapCheckPPMSCompliance:
    ppmsID: '73554900100200012406'
    createBuildVersion: true
    uploadChangeRequest: true
    runComplianceCheckWithDetect: true
    detectToken: 'token'
    blackduckProjectName: 'SHC - RESOURCE MGT OD 1.0'
    customScanVersion: 'C4P-RM-Master'
  checkmarxExecuteScan:
    projectName: 'SAP_C4PRM_RESOURCEMANAGEMENT_1.0'
    teamName: '\CxServer\SP\SAP\S4HANA_CLOUD\CLOUD_FOR_PROJECTS'
    serverUrl: 'https://cx.wdf.sap.corp'  
    preset: '100023'
    vulnerabilityThresholdHigh: 0
    vulnerabilityThresholdMedium: 10
    vulnerabilityThresholdLow: 50
    vulnerabilityThresholdUnit: 'absolute'
    incremental: false
  sapCheckECCNCompliance:
    ppmsID: '73554900100200012406'
