package com.sap.c4p.rm.assignment.config;

import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

public enum LoggingMarker {

  PRECOMPILER,
  CREATE_MARKER,
  CHANGE_MARKER,
  DELETE_MARKER,
  CAPACITY_GRID_MARKER,
  SIMULATION_MARKER,
  VALIDATION_MARKER,
  INTEGRATION_MARKER,
  INTEGRATION_CREATE_MARKER,
  INTEGRATION_DELETE_MARKER,
  INTEGRATION_CHANGE_MARKER,
  ERROR_PARSER_MARKER,
  SUBSCRIPTION_MARKER,
  AUDIT_MARKER,
  ASSIGNMENTASREQUESTED_SIMULATION_VALIDATOR_MARKER,
  TOTALHOURS_VALIDATOR,
  SUPPLYCOMMAND_MARKER,
  ASSIGNMENTUTILITY_MARKER,
  CONSULTANT_ASGN_UPDATE_MARKER,
  ASSIGNMENT_PUBLIC_API_MARKER;

  public Marker getMarker() {
    return MarkerFactory.getMarker(this.toString());
  }
}